### ISSUE TITLE
Freeze after =~ 2 minutes with OSP

### ISSUE THREAD

**Issue by goneri** [ioquake/ioq3#321]
Hi all,

Fedora 26 with Intel Corporation HD Graphics 5500.

ioquake from Fedora and from git freeze after about 2 minutes when I use it with OSP (osp-Quake3-1.03a_full.zip).

I tried to run it with: `+set s_useOpenAL 0 +set sv_pure 0 +set vm_cgame 0 +set vm_game 0 +set vm_ui 0 +set fs_game osp` and without. I can also reproduce the problem with a fresh configuration and with `cl_renderer=opengl1`. vq3 works just fine.

~~~
(gdb) bt full
#0  0x00007fffcc4d8087 in ?? ()
No symbol table info available.
#1  0x00007fffcc35f074 in ?? ()
No symbol table info available.
#2  0x00007fffcc4cc4d1 in ?? ()
No symbol table info available.
#3  0x00007fffcc35f074 in ?? ()
No symbol table info available.
#4  0x00007fffcc4b0476 in ?? ()
No symbol table info available.
#5  0x00007fffcc35f074 in ?? ()
No symbol table info available.
#6  0x00007fffcc4b09b8 in ?? ()
No symbol table info available.
#7  0x00007fffcc35f074 in ?? ()
No symbol table info available.
#8  0x00007fffcc37dbea in ?? ()
No symbol table info available.
#9  0x00007fffcc35f074 in ?? ()
No symbol table info available.
#10 0x00007fffcc35f66f in ?? ()
No symbol table info available.
#11 0x000000000055cc45 in VM_CallCompiled (vm=0x224a680 <vmTable>, args=0x7fffffffd370) at code/qcommon/vm_x86.c:1773
        stack = "ﾭ\336\360]\003\000\250\001\000\000\270\376\004\000d\364\037\000t\000\000\000\002\000\000\000\377\377\377\377\230\255w@\377\177\000\000\020\322\377\377\377\177\000\000`7d\005\000\000\000\000~\223\270\367\377\177\000\000p\317\377\377\377\177\000\000\345p\260\367\377\177\000\000\240\317\377\377\377\177\000\000\246\314\016\367\377\177\000\000\240\317\377\377\377\177\000\000\000\005\252\310\314Rе\300\317\377\377\377\177\000\000\000\000\000\000\000\000\000\000\001", '\000' <repeats 15 times>, "\006\000\000\000\000\000\000\000\022\371R\354\377\177\000\000\b\320\377\377\377\177\000\000\"v\260\367\377\177\000\000\020\322\377\377\377\177\000\000\000\005\252\310\314Rе\200\320\377\377\377\177\000\000\220\177e\005"...
        entryPoint = 0x7fffcc35f08b
        programStack = 2097092
        stackOnEntry = 2097152
        image = 0x7fffed74c088 <error: Cannot access memory at address 0x7fffed74c088>
        opStack = 0x7fffffffcef0
        opStackOfs = 0
        arg = 13
#12 0x000000000047aea4 in VM_Call (vm=0x224a680 <vmTable>, callnum=8) at code/qcommon/vm.c:862
        a = {callnum = 8, args = {31100, -177806032, -309018424, -311115640, 57923, 0, 0, 0, -10928, 4438847, -9616, 0}}
        ap = {{gp_offset = 48, fp_offset = 48, overflow_arg_area = 0x7fffffffd520, reg_save_area = 0x7fffffffd3f0}}
        oldVM = 0x224a680 <vmTable>
        r = 20
        i = 12
#13 0x000000000046df5b in SV_Frame (msec=12) at code/server/sv_main.c:1143
        frameMsec = 50
        startTime = 0
#14 0x000000000043bb3f in Com_Frame () at code/qcommon/common.c:3190
        msec = 12
        minMsec = 11
        timeVal = 0
        timeValSV = 2147483647
        lastTime = <error reading variable lastTime (Cannot access memory at address 0xb8bee0)>
        bias = <error reading variable bias (Cannot access memory at address 0xb8bee4)>
        timeBeforeFirstEvents = 0
        timeBeforeServer = 0
        timeBeforeEvents = 0
        timeBeforeClient = 0
        timeAfter = 0
#15 0x00000000004cb87c in main (argc=21, argv=0x7fffffffda78) at code/sys/sys_main.c:759
        i = 21
        commandLine = "\000exec goneri.cfg \000set s_useOpenAL 0 \000set sv_pure 0 \000set vm_cgame 0 \000set vm_game 0 \000set vm_ui 0 \000set fs_game osp ", '\000' <repeats 911 times>
        ver = {major = 2 '\002', minor = 0 '\000', patch = 5 '\005'}
~~~

**Comment by TimeDoctor** [comment]
This is more likely to be an issue with the graphics chipset or another support issue instead of a bug with ioquake3, please post on our forums http://discourse.ioquake.org
